import React, { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { Link, useNavigate, useSearchParams } from "react-router-dom";
import useSearchStore from "../stores/useSearchStore.js";
import Button from "../components/ui/Button.jsx";
import { finalizeBooking } from "../utils/api.js";
import { formatCurrency, formatDate } from "../utils/formatters.js";
import { trackOnce } from "../utils/analytics.js";

function normalizeTransactionId(searchParams) {
  return (
    searchParams.get("transactionId") ||
    searchParams.get("transactionID") ||
    searchParams.get("transaction_id") ||
    searchParams.get("payment_intent") || 
    ""
  );
}

function pickBookingDetails(payload) {
  const bookingWrapper = payload?.booking || payload?.data || payload;
  const bookingData = bookingWrapper?.data || bookingWrapper;

  const bookingId =
    bookingData?.bookingId ||
    bookingData?.bookingID ||
    bookingData?.reference ||
    bookingData?.id ||
    payload?.bookingId ||
    "";

  const hotelName =
    bookingData?.hotel?.name ||
    bookingData?.hotelName ||
    bookingData?.hotel?.hotelName ||
    "";

  const checkin = bookingData?.checkin || bookingData?.dates?.checkin || "";
  const checkout = bookingData?.checkout || bookingData?.dates?.checkout || "";

  const roomType =
    bookingData?.bookedRooms?.[0]?.roomType?.name || bookingData?.roomType || "";

  const amount =
    bookingData?.bookedRooms?.[0]?.rate?.retailRate?.total?.amount ||
    bookingData?.bookedRooms?.[0]?.rate?.retailRate?.total?.[0]?.amount ||
    bookingData?.totalAmount ||
    bookingData?.price?.gross ||
    bookingData?.price?.amount ||
    null;

  const currency =
    bookingData?.bookedRooms?.[0]?.rate?.retailRate?.total?.currency ||
    bookingData?.bookedRooms?.[0]?.rate?.retailRate?.total?.[0]?.currency ||
    bookingData?.price?.currency ||
    bookingData?.currency ||
    "";

  const guestName =
    bookingData?.holder?.firstName || bookingData?.holder?.lastName
      ? `${bookingData?.holder?.firstName || ""} ${
          bookingData?.holder?.lastName || ""
        }`.trim()
      : "";

  const hotelConfirmationNumber =
    bookingData?.hotelConfirmationNumber ||
    bookingData?.supplierBookingName ||
    "";

  const guestsSummary = (() => {
    const room = bookingData?.bookedRooms?.[0];
    const adults = room?.adults;
    const children = room?.children;
    if (typeof adults === "number" && typeof children === "number") {
      return `${adults} adult${adults === 1 ? "" : "s"}, ${children} child${
        children === 1 ? "" : "ren"
      }`;
    }
    if (typeof adults === "number") return `${adults} adult${adults === 1 ? "" : "s"}`;
    return "";
  })();

  return {
    bookingId,
    hotelName,
    checkin,
    checkout,
    roomType,
    amount,
    currency,
    guestName,
    guestsSummary,
    hotelConfirmationNumber,
    bookingData,
    bookingWrapper
  };
}

function Confirmation() {
  const [searchParams] = useSearchParams();
  const navigate = useNavigate();
  const { environment: defaultEnvironment } = useSearchStore();

  const prebookId = searchParams.get("prebookId") || "";
  const transactionId =
    searchParams.get("transactionId") || searchParams.get("payment_intent") || normalizeTransactionId(searchParams);
  const environment =
    searchParams.get("environment") || defaultEnvironment || "sandbox";

  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);
  const [bookingPayload, setBookingPayload] = useState(null);
  const finalizeInFlight = useRef(false);
  const [showDetails, setShowDetails] = useState(false);

  const details = useMemo(
    () => pickBookingDetails(bookingPayload),
    [bookingPayload]
  );

  const handleDownloadConfirmation = useCallback(() => {
    const title = "LuxeStayHaven Booking Confirmation";
    const safeBookingId = (details.bookingId || prebookId || "confirmation")
      .replace(/[^a-z0-9-_]/gi, "_")
      .slice(0, 48);

    const html = `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>${title}</title>
  <style>
    body{font-family:ui-sans-serif,system-ui,-apple-system,Segoe UI,Roboto,Helvetica,Arial; margin:32px; color:#0f172a;}
    h1{margin:0 0 12px; font-size:22px;}
    .muted{color:#475569; font-size:12px;}
    .card{border:1px solid #e2e8f0; border-radius:16px; padding:16px; margin-top:16px;}
    .grid{display:grid; grid-template-columns:repeat(2,minmax(0,1fr)); gap:12px;}
    .label{font-size:11px; text-transform:uppercase; letter-spacing:.12em; color:#64748b;}
    .value{font-size:14px; font-weight:600;}
  </style>
</head>
<body>
  <h1>${title}</h1>
  <div class="muted">Generated by LuxeStayHaven</div>
  <div class="card">
    <div class="grid">
      <div><div class="label">Booking Reference</div><div class="value">${details.bookingId || "—"}</div></div>
      <div><div class="label">Hotel Confirmation</div><div class="value">${details.hotelConfirmationNumber || "—"}</div></div>
      <div><div class="label">Hotel</div><div class="value">${details.hotelName || "—"}</div></div>
      <div><div class="label">Room</div><div class="value">${details.roomType || "—"}</div></div>
      <div><div class="label">Check-in</div><div class="value">${details.checkin || "—"}</div></div>
      <div><div class="label">Check-out</div><div class="value">${details.checkout || "—"}</div></div>
      <div><div class="label">Guests</div><div class="value">${details.guestsSummary || details.guestName || "—"}</div></div>
      <div><div class="label">Total Paid</div><div class="value">${
        details.amount != null && details.currency
          ? `${details.amount} ${details.currency}`
          : "—"
      }</div></div>
    </div>
  </div>
</body>
</html>`;

    const blob = new Blob([html], { type: "text/html;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `LuxeStayHaven-${safeBookingId}.html`;
    document.body.appendChild(a);
    a.click();
    a.remove();
    URL.revokeObjectURL(url);
  }, [details, prebookId]);

  const runFinalize = useCallback(async () => {
    if (!prebookId || !transactionId) return;
    if (finalizeInFlight.current) return;
    finalizeInFlight.current = true;

    setLoading(true);
    setError(null);

    try {
      const result = await finalizeBooking(prebookId, transactionId, environment);

      setBookingPayload(result);
    } catch (err) {
      setError(err.message || "Failed to confirm booking");
    } finally {
      setLoading(false);
      finalizeInFlight.current = false;
    }
  }, [prebookId, transactionId, environment]);

  useEffect(() => {
    if (!prebookId || !transactionId) return;
    runFinalize();
  }, [prebookId, transactionId, runFinalize]);

  useEffect(() => {
    if (loading || error || !bookingPayload) return;
    const revenue =
      details.amount != null && Number.isFinite(Number(details.amount)) ? Number(details.amount) : null;
    const currency = (details.currency || "USD").toUpperCase();
    trackOnce(`booking_complete:${details.bookingId || prebookId}`, "booking_complete", {
      booking_id: details.bookingId || prebookId || undefined,
      hotel_name: details.hotelName || undefined,
      currency,
      revenue: revenue == null ? undefined : revenue,
      value: revenue == null ? undefined : revenue
    });
  }, [bookingPayload, details.amount, details.bookingId, details.currency, details.hotelName, error, loading, prebookId]);

  if (!prebookId || !transactionId) {
    return (
      <section className="bg-background py-10 sm:py-12">
        <div className="max-w-2xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="rounded-3xl bg-white border border-slate-100 shadow-soft p-8 text-center">
            <div className="inline-flex items-center justify-center w-16 h-16 rounded-full bg-slate-50 text-slate-400 mb-4">
              <svg
                className="w-8 h-8"
                fill="none"
                viewBox="0 0 24 24"
                stroke="currentColor"
                strokeWidth={2}
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"
                />
              </svg>
            </div>
            <h1 className="font-heading text-2xl text-primary mb-2">
              No booking found
            </h1>
            <p className="text-sm text-textMedium mb-6">
              This page is shown after payment. Please return to the home page and
              make a new booking.
            </p>
            {!transactionId && prebookId && (
              <div className="mb-6 rounded-xl border border-warning/30 bg-warning/5 px-4 py-3 text-left text-xs text-warning">
                <div className="font-semibold">Debug</div>
                <div className="mt-1 break-all">
                  transactionId is missing from the URL. Current URL: {window.location.href}
                </div>
              </div>
            )}
            <Button type="button" onClick={() => navigate("/")}>
              Go home
            </Button>
          </div>
        </div>
      </section>
    );
  }

  return (
    <section className="bg-background py-10 sm:py-12">
      <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 space-y-6">
        <div className="rounded-3xl bg-white border border-slate-100 shadow-soft overflow-hidden">
          <div className="bg-success/5 p-8 text-center border-b border-slate-50">
            <div className="inline-flex items-center justify-center w-16 h-16 rounded-full bg-success text-white shadow-lg shadow-success/20">
              <svg
                className="w-9 h-9"
                fill="none"
                viewBox="0 0 24 24"
                stroke="currentColor"
                strokeWidth={3}
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  d="M5 13l4 4L19 7"
                />
              </svg>
            </div>
            <h1 className="mt-5 font-heading text-3xl text-primary">
              Booking confirmed
            </h1>
            <p className="mt-2 text-sm text-textMedium">
              Thank you for choosing LuxeStayHaven. We’re finalizing your booking
              details.
            </p>
          </div>

          <div className="p-8 space-y-6">
            <div className="grid sm:grid-cols-2 gap-4 text-xs text-textMedium">
              <div>
                <div className="text-textLight">Prebook ID</div>
                <div className="font-medium text-textDark break-all">
                  {prebookId}
                </div>
              </div>
              <div>
                <div className="text-textLight">Transaction ID</div>
                <div className="font-medium text-textDark break-all">
                  {transactionId}
                </div>
              </div>
            </div>

            {loading && (
              <div className="text-xs text-textMedium flex items-center gap-2">
                <span className="h-3.5 w-3.5 border-2 border-primary/20 border-t-primary rounded-full animate-spin" />
                Confirming your booking…
              </div>
            )}

            {error && (
              <div className="rounded-xl border border-error/30 bg-error/5 px-4 py-3 text-error text-xs">
                <div className="font-semibold">We couldn’t confirm your booking</div>
                <div className="mt-1">{error}</div>
                <div className="mt-3">
                  <Button type="button" variant="secondary" onClick={runFinalize}>
                    Retry
                  </Button>
                </div>
              </div>
            )}

            {!loading && !error && bookingPayload && (
              <div className="rounded-2xl bg-background px-5 py-5 space-y-5">
                <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-5 text-xs text-textMedium">
                  <div>
                    <div className="text-textLight">Booking reference</div>
                    <div className="font-semibold text-textDark break-all">
                      {details.bookingId || "—"}
                    </div>
                  </div>
                  <div>
                    <div className="text-textLight">Hotel confirmation</div>
                    <div className="font-medium text-textDark break-all">
                      {details.hotelConfirmationNumber || "—"}
                    </div>
                  </div>
                  <div>
                    <div className="text-textLight">Hotel</div>
                    <div className="font-medium text-textDark">
                      {details.hotelName || "—"}
                    </div>
                  </div>
                  <div>
                    <div className="text-textLight">Room</div>
                    <div className="font-medium text-textDark">
                      {details.roomType || "—"}
                    </div>
                  </div>
                  <div>
                    <div className="text-textLight">Check-in</div>
                    <div className="font-medium text-textDark">
                      {details.checkin ? formatDate(details.checkin) : "—"}
                    </div>
                  </div>
                  <div>
                    <div className="text-textLight">Check-out</div>
                    <div className="font-medium text-textDark">
                      {details.checkout ? formatDate(details.checkout) : "—"}
                    </div>
                  </div>
                  <div>
                    <div className="text-textLight">Guests</div>
                    <div className="font-medium text-textDark">
                      {details.guestsSummary || details.guestName || "—"}
                    </div>
                  </div>
                  <div>
                    <div className="text-textLight">Total paid</div>
                    <div className="font-semibold text-primary">
                      {details.amount != null && details.currency ? (
                        formatCurrency(details.amount, details.currency)
                      ) : (
                        "—"
                      )}
                    </div>
                  </div>
                </div>

                <div className="flex flex-col sm:flex-row gap-3">
                  <Button
                    type="button"
                    variant="secondary"
                    className="w-full sm:w-auto"
                    onClick={handleDownloadConfirmation}
                  >
                    Download confirmation
                  </Button>
                  <Button
                    type="button"
                    variant="secondary"
                    className="w-full sm:w-auto"
                    onClick={() => setShowDetails((v) => !v)}
                  >
                    View booking details
                  </Button>
                </div>

                {showDetails && (
                  <div className="rounded-xl border border-slate-200 bg-white p-4">
                    <div className="text-[11px] uppercase tracking-[0.18em] text-textLight font-semibold mb-2">
                      Booking payload
                    </div>
                    <pre className="text-[11px] text-textMedium overflow-auto max-h-[420px] whitespace-pre-wrap break-words">
                      {JSON.stringify(details.bookingWrapper, null, 2)}
                    </pre>
                  </div>
                )}

                <div className="text-[11px] text-textLight">
                  Environment: {environment}. A confirmation email will be sent to
                  the guest email address on the reservation.
                </div>
              </div>
            )}

            <div className="pt-1 flex flex-col sm:flex-row gap-3">
              <Link to="/search" className="flex-1">
                <Button type="button" className="w-full">
                  Book another stay
                </Button>
              </Link>
              <Link to="/" className="flex-1">
                <Button type="button" variant="secondary" className="w-full">
                  Go home
                </Button>
              </Link>
            </div>
          </div>
        </div>

        <div className="text-center text-[10px] text-textLight uppercase tracking-[0.28em] font-semibold">
          LuxeStayHaven · Secure Checkout
        </div>
      </div>
    </section>
  );
}

export default Confirmation;
